name: Auto Pull Request

on:
  push:
    branches:
      - main  # Altere para a branch que deseja monitorar

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Branch de destino do pull request
          title: Automated Pull Request
          body: Automated pull request created on push to main branch
